model: 'molnet'
dataset: 'chirality'

paths: 
  train_data: './data/ChirBase/sr_exp/chirbase_sr_clean_train.pkl' 
  valid_data: './data/ChirBase/sr_exp/chirbase_sr_clean_test.pkl'

model_para: 
  in_channels: 22
  num_atoms: 100
  encoder_layers: [64, 64, 128, 256, 512, 1024]
  emb_dim: 2048
  k: 5
  decoder_layers: [2048, 1024, 512, 256, 128, 64, 64, 64]
  dropout: 0.3
  out_channels: 1

train_para: 
  batch_size: 64
  epochs: 100
  lr: 0.0001
  num_workers: 0
  weight_decay: 0.9
  scheduler: 
    milestones: [10, 20, 40]
    gamma: 0.5
    