model: 'molnet'
dataset: 'chirality'

paths: 
  train_data: './data/Chirality/chirbase_clean_etkdg_train.sdf'
  valid_data: './data/Chirality/chirbase_clean_etkdg_test.sdf'
  all_data: './data/Chirality/chirbase_clean_etkdg.sdf' # for k-fold

model_para: 
  in_channels: 21
  num_atoms: 100
  num_add: 0
  encoder_layers: [64, 64, 128, 256, 512]
  emb_dim: 1024
  k: 5
  decoder_layers: [512, 256, 128, 64]
  dropout: 0.3
  csp_num: 1
  out_channels: 4

train_para:
  batch_size: 128
  accum_iter: 1
  epochs: 100
  lr: 0.00001
  num_workers: 0
  weight_decay: 0.001
  scheduler: 
    milestones: [20, 40, 80]
    gamma: 0.5
