model: 'molnet'
dataset: 'chirality'

paths: 
  train_data: './data/ChirBase_eo/exp/ad_sr_clean_train.sdf' 
  valid_data: './data/ChirBase_eo/exp/ad_sr_clean_test.sdf'

model_para: 
  in_channels: 21
  num_atoms: 100
  encoder_layers: [64, 64, 128, 256, 512, 1024]
  emb_dim: 2048
  k: 5
  decoder_layers: [512, 256, 128, 64]
  dropout: 0.3
  out_channels: 1

train_para:
  batch_size: 256
  epochs: 100
  lr: 0.0002
  num_workers: 0
  weight_decay: 0.01
  scheduler: 
    milestones: [10, 20, 40]
    gamma: 0.5
